# local-repo translation file
# Copyright (C) 2012 ushi
# This file is distributed under the same license as the local-repo package.
# 
# Translators:
# Jose M. Prieto <jmprieto@gmx.net>, 2012.
msgid ""
msgstr ""
"Project-Id-Version: local-repo\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2012-05-26 09:07+0200\n"
"PO-Revision-Date: 2012-05-26 08:21+0000\n"
"Last-Translator: martinkalcher <martin.kalcher@googlemail.com>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: es\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"

#: ../local-repo:30
msgid ""
"This program helps to manage local repositories. Specify the path to the\n"
"repository with the first argument. If no option is specified, some repo\n"
"information will be printed."
msgstr ""

#: ../local-repo:33
#, python-format
msgid "%(prog)s path [options]"
msgstr "%(prog)s ruta [opciones]"

#: ../local-repo:39 ../local-repo:42 ../local-repo:65
msgid "path"
msgstr "ruta"

#: ../local-repo:40
msgid "path to the repo or the repo name if set up in your config file '{0}'"
msgstr ""

#: ../local-repo:43
msgid ""
"add a package to the repo - path can point to a local or remote package "
"file, pkgbuild file or pkgbuild tarball - supported protocols are HTTP(S) "
"and FTP"
msgstr ""

#: ../local-repo:46 ../local-repo:49 ../local-repo:68 ../local-repo:74
msgid "name"
msgstr "paquete"

#: ../local-repo:47
msgid "download, build and add a package from the AUR to the repo"
msgstr "descarga un paquete del AUR, lo compila y lo añade al repositorio"

#: ../local-repo:50
msgid ""
"rebuild specified packages - NOTE: the 'pkgbuild' path must be set up in the"
" config file"
msgstr ""

#: ../local-repo:54
msgid "run an integrity check"
msgstr "hace una comprobación de integridad"

#: ../local-repo:57
msgid "clear the cache"
msgstr "limpia la caché"

#: ../local-repo:60
msgid "the elephant never forgets"
msgstr "el elefante nunca olvida"

#: ../local-repo:63
msgid ""
"force an operation - use this with -a or --add to up-/downgrade a package"
msgstr ""

#: ../local-repo:66
msgid "use an alternative config file (instead of '{0}')"
msgstr ""

#: ../local-repo:69
msgid "display info for specified packages"
msgstr "muestra información de los paquetes especificados"

#: ../local-repo:72
msgid "list all packages from the repo"
msgstr "lista todos los paquetes del repositorio"

#: ../local-repo:75
msgid "remove packages from the repo"
msgstr "quita paquetes del repositorio"

#: ../local-repo:78
msgid "restore repo database"
msgstr ""

#: ../local-repo:80
msgid "term"
msgstr "término"

#: ../local-repo:81
msgid "find packages"
msgstr "busca paquetes"

#: ../local-repo:84
msgid "upgrade all packages in the repo, which are available in the AUR"
msgstr "actualiza todos los paquetes del repositorio que estén disponibles en el AUR"

#: ../local-repo:87
msgid ""
"upgrade all packages in the repo, which are based on a VCS and available in "
"the AUR"
msgstr "actualiza todos los paquetes del repositorio alojados en un VCS que estén disponibles en el AUR"

#: ../localrepo/aur.py:104
msgid "Could not reach the AUR"
msgstr "No se pudo acceder al AUR"

#: ../localrepo/aur.py:107 ../localrepo/aur.py:117
msgid "AUR responded with error: {0}"
msgstr "El AUR respondió con el error: {0}"

#: ../localrepo/aur.py:114 ../localrepo/aur.py:125
msgid "AUR responded with invalid data"
msgstr "El AUR respondió con datos no válidos"

#: ../localrepo/config.py:55
msgid "Could not open config file: {0}"
msgstr ""

#: ../localrepo/config.py:60
msgid "Could not parse config file: {0}"
msgstr ""

#: ../localrepo/config.py:151
msgid "Could not save config file: {0}"
msgstr ""

#: ../localrepo/localrepo.py:35
msgid "Execution cancelled by user"
msgstr "Ejecución cancelada por el usuario"

#: ../localrepo/localrepo.py:53
msgid "Loading repo: {0}"
msgstr ""

#: ../localrepo/localrepo.py:69
msgid "This repo has no packages"
msgstr "Este repositorio no contiene paquetes"

#: ../localrepo/localrepo.py:80
msgid "Package does not exist: {0}"
msgstr ""

#: ../localrepo/localrepo.py:83
msgid "Package information: {0}"
msgstr ""

#: ../localrepo/localrepo.py:92
msgid "No package found"
msgstr "No se encontraron paquetes"

#: ../localrepo/localrepo.py:101
msgid ""
"Need following packages as dependencies:\n"
"[{0}]"
msgstr ""

#: ../localrepo/localrepo.py:103
msgid "Install?"
msgstr ""

#: ../localrepo/localrepo.py:104
msgid "Try without installing dependencies?"
msgstr ""

#: ../localrepo/localrepo.py:107 ../localrepo/localrepo.py:238
#: ../localrepo/localrepo.py:267
msgid "Bye"
msgstr "Adiós"

#: ../localrepo/localrepo.py:119
msgid ""
"Installed following packages as dependencies:\n"
"[{0}]"
msgstr ""

#: ../localrepo/localrepo.py:121
msgid "Uninstall?"
msgstr ""

#: ../localrepo/localrepo.py:130 ../localrepo/localrepo.py:131
msgid "Forging a new package: {0}"
msgstr ""

#: ../localrepo/localrepo.py:158
msgid "Adding package to the repo: {0}"
msgstr ""

#: ../localrepo/localrepo.py:160
msgid "Added Package: {0} {1}"
msgstr ""

#: ../localrepo/localrepo.py:168
msgid "Please specify 'pkgbuild' in your config file!"
msgstr ""

#: ../localrepo/localrepo.py:178
msgid "Packages do not exist: {0}"
msgstr ""

#: ../localrepo/localrepo.py:181
msgid "Removing packages: {0}"
msgstr ""

#: ../localrepo/localrepo.py:185
msgid "Removed packages: {0}"
msgstr ""

#: ../localrepo/localrepo.py:192 ../localrepo/localrepo.py:216
#: ../localrepo/localrepo.py:254
msgid "Retrieving package info from the AUR"
msgstr "Recuperando información de los paquetes desde el AUR"

#: ../localrepo/localrepo.py:200 ../localrepo/repo.py:80
msgid "Package is already in the repo: {0}"
msgstr "El paquete ya está en el repositorio: {0}"

#: ../localrepo/localrepo.py:209 ../localrepo/localrepo.py:222
#: ../localrepo/localrepo.py:286
msgid "{0} packages found"
msgstr "{0} paquetes encontrados"

#: ../localrepo/localrepo.py:210
msgid "Starting an AUR upgrade"
msgstr ""

#: ../localrepo/localrepo.py:213
msgid "Nothing to do"
msgstr "Nada que hacer"

#: ../localrepo/localrepo.py:223
msgid "Checking for updates"
msgstr "Comprobando actualizaciones"

#: ../localrepo/localrepo.py:234
msgid "All packages are up to date"
msgstr "Todos los paquetes están actualizados"

#: ../localrepo/localrepo.py:237 ../localrepo/localrepo.py:266
msgid "Upgrade?"
msgstr ""

#: ../localrepo/localrepo.py:246
msgid "Updating all VCS packages"
msgstr "Actualizando todos los paquetes de VCS"

#: ../localrepo/localrepo.py:247
msgid "Starting a VCS upgrade"
msgstr ""

#: ../localrepo/localrepo.py:251
msgid "No VCS packages found"
msgstr "No se encontraron paquetes de VCS"

#: ../localrepo/localrepo.py:261
msgid "No updates found"
msgstr ""

#: ../localrepo/localrepo.py:275
msgid "Clearing the cache"
msgstr "Borrando la caché"

#: ../localrepo/localrepo.py:279
msgid "Cleared cache"
msgstr ""

#: ../localrepo/localrepo.py:287
msgid "Running integrity check"
msgstr "Comprobando la integridad"

#: ../localrepo/localrepo.py:291
msgid "No errors found"
msgstr "No se encontraron errores"

#: ../localrepo/localrepo.py:292
msgid "Finished integrity check without any errors"
msgstr ""

#: ../localrepo/localrepo.py:295
msgid "Finished integrity check with errors:"
msgstr ""

#: ../localrepo/localrepo.py:304
msgid "Restoring database"
msgstr "Restaurando la base de datos"

#: ../localrepo/localrepo.py:308
msgid "Restored Database"
msgstr ""

#: ../localrepo/log.py:52
msgid "Could not open log file: {0}"
msgstr ""

#: ../localrepo/log.py:65
msgid "[Error] {0}"
msgstr ""

#: ../localrepo/log.py:104
msgid "Could not store log file: {0} -> {1}"
msgstr ""

#: ../localrepo/log.py:140
msgid "Could not copy PKGBUILD dir: {0} -> {1}"
msgstr ""

#: ../localrepo/package.py:35
msgid "Unresolved dependencies: {0}"
msgstr "Dependencias no resueltas: {0}"

#: ../localrepo/package.py:101
msgid "Could not download file: {0}"
msgstr "No se pudo descargar el archivo: {0}"

#: ../localrepo/package.py:113
msgid "Could not open tarball: {0}"
msgstr ""

#: ../localrepo/package.py:120
msgid "Tarball contains bad member: {0}"
msgstr "El tarball contiene una entrada no válida: {0}"

#: ../localrepo/package.py:142
msgid "Could not extract tarball: {0}"
msgstr ""

#: ../localrepo/package.py:169 ../localrepo/repo.py:130
#: ../localrepo/repo.py:150 ../localrepo/repo.py:198
msgid "Could not list directory: {0}"
msgstr ""

#: ../localrepo/package.py:191
msgid "Could not find PKGBUILD: {0}"
msgstr ""

#: ../localrepo/package.py:211
msgid "Could not find any package: {0}"
msgstr ""

#: ../localrepo/package.py:237
msgid "File does not exist: {0}"
msgstr "El archivo no existe: {0}"

#: ../localrepo/package.py:245
msgid "Could not read package info: {0}"
msgstr ""

#: ../localrepo/package.py:253
msgid "An error occurred in tar"
msgstr "Ocurrió un error en tar"

#: ../localrepo/package.py:267
msgid "Could not determine package size: {0}"
msgstr ""

#: ../localrepo/package.py:269
msgid "Could not calculate package checksums: {0}"
msgstr ""

#: ../localrepo/package.py:288
msgid "Invalid file name: {0}"
msgstr "Nombre de archivo no válido: {0}"

#: ../localrepo/package.py:373
msgid "Destination is no directory: {0}"
msgstr "El destino no es un directorio: {0}"

#: ../localrepo/package.py:381
msgid "File already exists: {0}"
msgstr "El archivo ya existe: {0}"

#: ../localrepo/package.py:387
msgid "Could not move package: {0} -> {1}"
msgstr ""

#: ../localrepo/package.py:398
msgid "Could not move sig file: {0} -> {1}"
msgstr ""

#: ../localrepo/package.py:409
msgid "Could not remove package: {0}"
msgstr ""

#: ../localrepo/pacman.py:20
msgid "An error occurred while running: {0}"
msgstr "Ocurrió un error durante la ejecución: {0}"

#: ../localrepo/pacman.py:102
msgid "Could not change working directory: {0}"
msgstr ""

#: ../localrepo/pacman.py:143
msgid "Ooh no! Somebody killed the repo elephant"
msgstr "¡Ooh no! Alguien mató al elefante del repositorio"

#: ../localrepo/parser.py:55 ../localrepo/parser.py:62
msgid "Could not parse PKGBUILD: {0}"
msgstr ""

#: ../localrepo/parser.py:69
msgid "Missing PKGBUILD entry: {0}"
msgstr ""

#: ../localrepo/parser.py:98
msgid "Missing PKGINFO entry: {0}"
msgstr ""

#: ../localrepo/parser.py:123
msgid "Missing fields: {0}"
msgstr ""

#: ../localrepo/repo.py:91
msgid "Could not add packages to the db: {0}"
msgstr ""

#: ../localrepo/repo.py:108
msgid "Could not remove packages from the db: {0}"
msgstr ""

#: ../localrepo/repo.py:120
msgid "Package has no valid checksum: {0}"
msgstr "El paquete no contiene una suma de verificación válida: {0}"

#: ../localrepo/repo.py:123
msgid "Missing signature for package: {0}"
msgstr ""

#: ../localrepo/repo.py:128
msgid "Package is not listed in repo database: {0}"
msgstr "El paquete no está en la base de datos del repositorio: {0}"

#: ../localrepo/repo.py:145
msgid "Could not find database: {0}"
msgstr ""

#: ../localrepo/repo.py:170
msgid "Could not open database: {0}"
msgstr ""

#: ../localrepo/repo.py:179
msgid "Invalid db entry: {0}: {1}"
msgstr ""

#: ../localrepo/repo.py:181
msgid "Could not read db entry: {0}"
msgstr ""

#: ../localrepo/repo.py:189
msgid "Could not close database: {0}"
msgstr ""

#: ../localrepo/repo.py:206
msgid "Could not remove database: {0}"
msgstr ""

#: ../localrepo/repo.py:217 ../localrepo/repo.py:219
msgid "Cache is outdated: {0}"
msgstr ""

#: ../localrepo/repo.py:225
msgid "Could not load cache: {0}"
msgstr ""

#: ../localrepo/repo.py:237
msgid "Could not update cache: {0}"
msgstr ""

#: ../localrepo/repo.py:245
msgid "Could not clear cache: {0}"
msgstr ""

#: ../localrepo/utils.py:96
msgid "[y|N]"
msgstr ""

#: ../localrepo/utils.py:97
msgid "y"
msgstr ""

#: ../localrepo/utils.py:97
msgid "yes"
msgstr ""

#: ../localrepo/utils.py:110
msgid "Architecture"
msgstr "Arquitectura"

#: ../localrepo/utils.py:111
msgid "Bugs"
msgstr ""

#: ../localrepo/utils.py:112
msgid "Build Date"
msgstr "Fecha de creación"

#: ../localrepo/utils.py:113
msgid "Package size"
msgstr "Tamaño del paquete"

#: ../localrepo/utils.py:114
msgid "Description"
msgstr "Descripción"

#: ../localrepo/utils.py:115
msgid "Filename"
msgstr "Nombre de archivo"

#: ../localrepo/utils.py:116
msgid "Installed size"
msgstr "Tamaño instalado"

#: ../localrepo/utils.py:117
msgid "Last update"
msgstr "Última actualización"

#: ../localrepo/utils.py:118
msgid "License"
msgstr "Licencia"

#: ../localrepo/utils.py:119
msgid "Location"
msgstr "Ubicación"

#: ../localrepo/utils.py:120
msgid "MD5sum"
msgstr "MD5sum"

#: ../localrepo/utils.py:121
msgid "Name"
msgstr "Nombre"

#: ../localrepo/utils.py:122
msgid "Packager"
msgstr "Empaquetador"

#: ../localrepo/utils.py:123
msgid "Packages"
msgstr "Paquetes"

#: ../localrepo/utils.py:124
msgid "Signed"
msgstr ""

#: ../localrepo/utils.py:125
msgid "SHA256sum"
msgstr "SHA256sum"

#: ../localrepo/utils.py:126
msgid "Translations"
msgstr ""

#: ../localrepo/utils.py:127
msgid "URL"
msgstr "URL"

#: ../localrepo/utils.py:128
msgid "Version"
msgstr "Versión"

#: ../localrepo/utils.py:129
msgid "Website"
msgstr ""

#: ../localrepo/utils.py:157
msgid "Yes"
msgstr ""

#: ../localrepo/utils.py:157
msgid "No"
msgstr ""

# Additional messages from the argparse module
# See: /usr/lib/python3.2/argparse.py
msgid "usage: "
msgstr "uso: "

msgid "positional arguments"
msgstr "argumentos posicionales"

msgid "optional arguments"
msgstr "argumentos opcionales"

msgid "show this help message and exit"
msgstr "muestra esta ayuda y sale"

msgid "too few arguments"
msgstr "faltan argumentos"

msgid "unrecognized arguments: %s"
msgstr "argumentos no reconocidos: %s"

msgid "expected at least one argument"
msgstr "se esperaba al menos un argumento"

msgid "%(prog)s: error: %(message)s\n"
msgstr "%(prog)s: error: %(message)s\n"
